### ISSUE TITLE
Volume control example is inconsistent/Doesn't work

### ISSUE THREAD

**Issue by Damglador** [taj-ny/kwin-gestures#16]
I did cmake uninstall, deleted cloned repo, ran 
```
git clone https://github.com/taj-ny/kwin-gestures
cd kwin-gestures
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
```
Plugin installed, I turned it on, cleared my config (tho it worked and didn't break, just to make testing clear), ran ``qdbus org.kde.KWin /Effects org.kde.kwin.Effects.reconfigureEffect kwin_gestures`` and tried gestures. A demonstration is in video below.

https://github.com/user-attachments/assets/392afe77-5510-43f8-af83-6af3f109ce89

**Comment by taj-ny** [comment]
You need to restart Plasma after updating the effect, I forgot to mention that.

**Comment by Damglador** [comment]
> You need to restart Plasma after updating the plugin, I forgot to mention that.

Yup, that was the issue. I'll go remake my config now
