### ISSUE TITLE
A way to debug the plugin

### ISSUE THREAD

**Issue by Damglador** [taj-ny/kwin-gestures#5]
I want to add gestures for:

3 finger
- swipe up - volume up (pactl set-sink-volume @DEFAULT_SINK@ +5%)
- swipe down - volume down (pactl set-sink-volume @DEFAULT_SINK@ -5%)
- swipe left - previous track
- swipe right - next track
- touch - pause/resume

I have no clue what I'm doing, guide is not the clearest and lack of logs makes it worse, because examples dont work and I cant even know why.

I did:
```
git clone https://github.com/taj-ny/kwin-gestures
cd kwin-gestures
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
```
- Edited `/home/damglador/.config/kwingesturesrc` to add 
```
[Gestures][Touchpad][Firefox Back]
Type=Swipe
Fingers=3
TriggerWhenThresholdReached=true
WindowRegex=firefox

[Gestures][Touchpad][Firefox Back][Swipe]
Direction=Left
ThresholdX=10

[Gestures][Touchpad][Firefox Back][Actions][0]
Type=KeySequence

[Gestures][Touchpad][Firefox Back][Actions][0][KeySequence]
Sequence=press LEFTCTRL,press LEFTBRACE,release LEFTCTRL,release LEFTBRACE
```
- Enabled the plugin in Desktop Effects
- Tabbed to Firefox and tried the gesture
- Nothing happend

I've tried creating a config for volume up gesture:
```
[Gestures][Touchpad][Volume Up]
Type=Swipe
Fingers=3
TriggerWhenThresholdReached=true
[Gestures][Touchpad][Volume Up][Swipe]
Direction=Up
Threshold=0.5
[Gestures][Touchpad][Volume Up][Actions][0]
Type=Command
[Gestures][Touchpad][Volume Up][Actions][0][Command]
Command="pactl set-sink-volume @DEFAULT_SINK@ +5%"
```
And I don't know how to know what's wrong

Distro: Arch Linux
Plasma version: 6.2

**Comment by taj-ny** [comment]
Are you on Wayland or X11?

Try running ``qdbus org.kde.KWin /Effects org.kde.kwin.Effects.reconfigureEffect kwin_gestures`` and try again. If that doesn't work, run ``libinput debug-events`` as root and check if the gesture is being recognized properly. You should see something like this:
```
event13  GESTURE_SWIPE_UPDATE    +16609.969s   3 -0.18/-2.80 (-0.18/-2.80 unaccelerated)
```
The 3 is the amount of fingers.

There are a couple of issues with the volume up gesture:
- ``Threshold`` should be ``ThresholdY``
- ``Threshold`` is an integer, not a float
-  ``Command`` doesn't need quotes, unless you're running something like ``/bin/sh -c "command"``

The last issue is what's preventing the gesture from working.

**Comment by Damglador** [comment]
> Are you on Wayland or X11?
Yes

> The last issue is what's preventing the gesture from working.
Yes, removing them fixed it.

Thank you. I got everything to work:
[kwingesturesrc.txt](https://github.com/user-attachments/files/17356069/kwingesturesrc.txt)

You may include in examples, perhaps other ppl will use it.

Also, is there a way to repeat an action? Something like `TriggerWhenThresholdReached=true` and `Repeat=50` so it repeats every 50ms instead of on release. Would be handy to control audio volume.

**Comment by taj-ny** [comment]
> Also, is there a way to repeat an action? Something like TriggerWhenThresholdReached=true and Repeat=50 so it repeats every 50ms instead of on release. Would be handy to control audio volume.
Not yet, I'll add it.

Also, I just figured out why the Firefox shortcut didn't work, it's because of keyboard layouts.

**Comment by Damglador** [comment]
> Not yet, I'll add it.

Nice, thanks

> Also, I just figured out why the Firefox gesture didn't work, it's because of keyboard layouts.

Well, I got unlucky with choice for test action and that gaslighted me to think nothing works.

**Comment by Damglador** [comment]
Libinput also has a weird quirk, it has a pretty long delay before it registers "hold". As I understand, even with delay 1ms in config, it will trigger only after 10ms minimum. Bearable.

**Comment by taj-ny** [comment]
> Also, is there a way to repeat an action? Something like TriggerWhenThresholdReached=true and Repeat=50 so it repeats every 50ms instead of on release. Would be handy to control audio volume.

You can now do that on the master branch, there's an example at [docs/example_gestures.md](https://github.com/taj-ny/kwin-gestures/blob/main/docs/example_gestures.md). See #9 for breaking config changes. v0.3.0 should be out tomorrow, I still need to do some testing.

**Comment by Damglador** [comment]
Poggers, will test it tomorrow.
